name: Sync Subtrees
description: Pulls/pushes subtrees from a `.github/subtrees.json` file.
author: Your Name or Org
inputs:
  dryRun:
    description: 'If true, don’t push any changes (for testing only).'
    required: true
    default: 'true'
  testMerge:
    description: 'Run in test mode, pushing to a test branch.'
    required: true
    default: 'false'
  # repo:
  #   description: 'Repository name'
  #   required: true
  defaultRef:
    description: 'Default branch name'
    required: true
  runNumber:
    description: 'GitHub run number'
    required: true
  # authToken:
  #   description: 'GitHub PAT with repo access'
  #   required: true
  sshKey:
    description: 'SSH private key for authentication'
    required: true
  repoOwner:
    required: true
  repoName:
    description: 'Repository name'
    required: true
  testRef:
    description: 'Test branch name'
    required: false


runs:
  using: docker
  image: Dockerfile
  env:
    CI_SERVER_HOST: github.com
    # GROUP: ${{ github.repository_owner }}
    # REPO_NAME: ${{ github.repository.name }}
    TEST_MERGE: ${{ inputs.testMerge }}
    DRY_RUN: ${{ inputs.dryRun }}
    REPO_NAME: ${{ inputs.repoName }}
    GROUP: ${{ inputs.repoOwner }}
    RUN_NUMBER: ${{ inputs.runNumber }}
    DEFAULT_REF: ${{ inputs.defaultRef }}
    TEST_REF: _gha-${{ inputs.repoName }}-sync-subtrees-${{ inputs.runNumber }}
    SSH_KEY: ${{ inputs.sshKey }}
  args: []
