name: Sync Subtrees
description: Pulls/pushes subtrees from a `.github/subtrees.json` file.
author: Your Name or Org
inputs:
  dryRun:
    description: 'If true, don’t push any changes (for testing only).'
    required: true
    default: 'true'
  testMerge:
    description: 'Run in test mode, pushing to a test branch.'
    required: true
    default: 'false'
  # repo:
  #   description: 'Repository name'
  #   required: true
  defaultRef:
    description: 'Default branch name'
    required: true
  # runNumber:
  #   description: 'GitHub run number'
  #   required: true
  # authToken:
  #   description: 'GitHub PAT with repo access'
  #   required: true
  sshKey:
    description: 'SSH private key for authentication'
    required: true


runs:
  using: docker
  image: Dockerfile
  env:
    CI_SERVER_HOST: github.com
    GROUP: ${{ github.repository_owner }}
    REPO_NAME: ${{ github.repository.name }}
    RUN_NUMBER: ${{ github.run_number }}
  args: []
